name: Spring Boot Unit Tests

on:
  pull_request:
  branch_protection_rule:
    types: [ created, deleted ]
  check_run:
    types:
      - created
      - rerequested

jobs:
  unit-test:
    runs-on: ubuntu-latest

    outputs:
      job-status: ${{ steps.run-tests.outputs.job-status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 20.0.1
        uses: actions/setup-java@v1
        with:
          java-version: 20.0.1

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore Gradle build caches
        id: gradle-cache-restore
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Checkout code
        if: steps.gradle-cache-restore.outputs.cache-hit != 'true'
        uses: actions/checkout@v2

      - name: Rerun build job
        if: steps.gradle-cache-restore.outputs.cache-hit != 'true'
        uses: ./.github/workflow/build.yml
        continue-on-error: false

      - name: Run Tests
        id: run-tests
        run: ./gradlew test --stacktrace
